//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_analyzer_
    {
        public int id { get; set; }
        public Nullable<int> id_analyzer { get; set; }
        public Nullable<System.DateTime> dateTime_receipt { get; set; }
        public Nullable<int> due_time { get; set; }
        public Nullable<int> id_s_in_o { get; set; }
        public Nullable<int> id_lab { get; set; }
    
        public virtual analyzer_ analyzer_ { get; set; }
        public virtual s_in_o_ s_in_o_ { get; set; }
        public virtual users_ users_ { get; set; }
    }
}
