//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabEntities : DbContext
    {
        public LabEntities()
            : base("name=LabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analyzer_> analyzer_ { get; set; }
        public virtual DbSet<cause_> cause_ { get; set; }
        public virtual DbSet<check_> check_ { get; set; }
        public virtual DbSet<data_analyzer_> data_analyzer_ { get; set; }
        public virtual DbSet<insurance_company_> insurance_company_ { get; set; }
        public virtual DbSet<order_> order_ { get; set; }
        public virtual DbSet<policy_> policy_ { get; set; }
        public virtual DbSet<role_> role_ { get; set; }
        public virtual DbSet<s_in_o_> s_in_o_ { get; set; }
        public virtual DbSet<services_> services_ { get; set; }
        public virtual DbSet<status_> status_ { get; set; }
        public virtual DbSet<story_> story_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users_> users_ { get; set; }
    }
}
