//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_()
        {
            this.s_in_o_ = new HashSet<s_in_o_>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> lead_time { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual status_ status_ { get; set; }
        public virtual users_ users_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<s_in_o_> s_in_o_ { get; set; }
    }
}
