//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class story_
    {
        public int id { get; set; }
        public Nullable<int> id_user { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> startenter { get; set; }
        public Nullable<System.DateTime> lastenter { get; set; }
        public Nullable<int> id_cause { get; set; }
    
        public virtual cause_ cause_ { get; set; }
        public virtual users_ users_ { get; set; }
    }
}
