//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users_()
        {
            this.check_ = new HashSet<check_>();
            this.data_analyzer_ = new HashSet<data_analyzer_>();
            this.order_ = new HashSet<order_>();
            this.story_ = new HashSet<story_>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> type_policy { get; set; }
        public string telephone { get; set; }
        public string e_mail { get; set; }
        public string passport_series { get; set; }
        public string passport_number { get; set; }
        public string policy_number { get; set; }
        public Nullable<int> insurance_company { get; set; }
        public Nullable<int> role { get; set; }
        public string avatar { get; set; }
        public string FullName
        {
            get { return $"{name} {surname}"; }

        }

        public Nullable<System.DateTime> date_birth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<check_> check_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<data_analyzer_> data_analyzer_ { get; set; }
        public virtual insurance_company_ insurance_company_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_> order_ { get; set; }
        public virtual policy_ policy_ { get; set; }
        public virtual role_ role_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<story_> story_ { get; set; }
    }
}
